# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: WebApp-SQL
version: 1.0.0
summary: Azure Web App Environment with a data store
description: Deploys an Azure Web App with a data store
runner: ARM
templatePath: websql.json
parameters:
  - id: siteName
    name: siteName
    description: 'Name of the Web App.'
    type: string
    required: true
  - id: administratorLogin
    name: administratorLogin
    description: 'Database administrator login name'
    type: string
    required: true
  - id: administratorLoginPassword
    name: administratorLoginPassword
    description: 'Database administrator password'
    type: string
    required: true
  - id: sqlDBName
    name: sqlDBName
    description: 'Azure database for sql db name'
    type: string
    required: true
  - id: serverName
    name: serverName
    description: 'Azure Serve name'
    type: string
    required: true
  - id: location
    name: location
    description: 'Location for all resources.'
    type: string
    required: true



